# ENGLISH _____________________________
  [Languages.it]
    lang = "Italiano"
    LanguageCode = "it"
    title = "Litecoin - Valuta digitale P2P Open source"
    weight = 12

  # Hero section
  [Languages.it.hero]
    # title = "Global Decentralized Currency"
    # subtitle = "Based on Blockchain Technology"

  # Navigation
  [Languages.it.navigation]
    brand = "litecoin"
    download = "SCARICARE"
    about = "About"
    team = "Team"
    contact = "Contact"

    # postpended links
    [[menu.postpend]]
      url = "https://litecointalk.io/"
      name = "Forum"
      weight = 10


  # About section
  [Languages.it.about]
    enable = true
    title = "Che cos’è Litecoin?"
    subtitle = "Litecoin è una valuta digitale peer-to-peer che permette pagamenti istantanei quasi a zero costo a favore di un destinatario, ovunque esso si trovi. Litecoin è una rete di pagamenti globali, open source, pienamente decentralizzata e senza autorità centrale. La matematica garantisce la rete stessa trasferendo agli individui la sovranità sul controllo delle proprie finanze. Litecoin può vantare, rispetto al Bitcoin, una maggiore frequenza nella conferma delle transazioni e una migliore efficienza nella conservazione dei dati. Forte di ampio supporto, elevata liquidità ed alti volumi, Litecoin è un consolidato mezzo di scambio complementare al Bitcoin."

    [[Languages.it.about.row]]
      [[Languages.it.about.row.list]]
        icon = "fa-group"
        title = "Comunità"
        description =  '<p class="text-no-margin text-left text-muted">Esiste una serie di comunità Litecoin in crescita dove potete trovare assistenza. Potete visitare: </p><ul class="text-muted text-left "> <li><a href="https://litecointalk.org">I Forum di Litecoin</a></li> <li><a href="http://www.reddit.com/r/litecoin">La Comunità Reddit di Litecoin</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">• Cerca Utenti su Twitter</a></li> <li>Iscrivetevi al canale della rete <a href="http://freenode.net/" rel="nofollow">IRC FreeNode</a> <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (per utenti in generale) e <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (per sviluppatori).</li> </ul>'

      [[Languages.it.about.row.list]]
        icon = "fa-laptop"
        title = "Risorse"
        description = 'Informazioni di carattere generale, elenchi di siti e di servizi che supportano Litecoin si possono trovare sul <a href="http://litecoin.info">Litecoin Wiki</a>. <br> Statistiche di rete aggiornate si possono trovare nei grafici del <a href="http://ltc.block-explorer.com/charts">Block Explorer Litecoin</a>. <br> Il codice sorgente di Litecoin ed altri progetti collegati sono disponibili su <a href="https://github.com/litecoin-project">GitHub.com/litecoin-project</a>.'

      [[Languages.it.about.row.list]]
        icon = "fa-heart"
        title = "Software Open Source"
        description = "Litecoin è un progetto open source rilasciato sotto la licenza MIT/X11 la quale vi permette di eseguire, modificare, copiare il software e di distribuirne, a vostra scelta, versioni aggiornate. Il software viene rilasciato secondo modalità trasparenti che permettono la verifica indipendente dei codici binari e dei loro corrispondenti codici sorgente."

    [[Languages.it.about.row]]
      [[Languages.it.about.row.list]]
        icon = "fa-link"
        title = "Catena di blocchi"
        description = "La Catena di blocchi di Litecoin è in grado di gestire volumi di transazioni superiori rispetto alla sua controparte - Bitcoin. A causa della più frequente generazione dei blocchi, la rete è in grado di supportare un numero maggiore di transazioni senza che il software debba essere modificato in futuro. <br />Ne deriva che i commercianti ottengono tempi di conferma più rapidi, mentre conservano la possibilità di aspettare altre conferme, quando vendono articoli a prezzo più alto."

      [[Languages.it.about.row.list]]
        icon = "fa-lock"
        title = "Cifratura del Portafoglio"
        description = "La Cifratura del Portafoglio vi permette di proteggere le vostre chiavi private, in modo tale da avere sempre la possibilità di visualizzare le transazioni e il saldo del vostro conto, mentre vi verrà richiesto di inserire la vostra password prima di poter spendere i vostri litecoin. <br />Questo serve non solo come misura di protezione contro i virus e i cavalli di troia, ma anche come un controllo di sicurezza prima che inviate dei pagamenti."

      [[Languages.it.about.row.list]]
        icon = "fa-money"
        title = "Ricompensa"
        description = "I miner all'inizio genereranno 25 monete per blocco. La quantità di monete generate viene dimezzata ogni 4 anni (840.000 blocchi). <br />Pertanto, la rete Litecoin è programmata per produrre approssimativamente il quadruplo di unità rispetto a Bitcoin, ovvero circa 84 milioni di litecoin."

  # download section
  [Languages.it.download]
    enable = true
    gpg = "GPG Signatures"
    download = "SCARICARE"
    source = "SORGENTE"
    releaseNotes = "Release Notes"
    upgradeNotes = "Upgrade Notes"

    windows = "per Windows"
    mac = "per Mac OS X"
    linux = "per Linux"
    android = "Litecoin per Android"
    blackberry = "Litecoin per Blackberry"
    electrum = "Electrum Litecoin"


  # Contact section
  [Languages.it.contact]
    enable = true
    # title = "Contact us"
    subtitle  = "Potete contattare il team degli sviluppatori di Litecoin all'indirizzo di posta elettronica <a href=\"mailto:contact@litecoin.org\">contact@litecoin.org</a>."

  # Footer section
  [Languages.it.footer]
    enable = true
    copyright = "Copyright &copy; 2011-2016 Litecoin Project. Tutti i Diritti Riservati."
