# ENGLISH _____________________________
  [Languages.pt]
    lang = "Português"
    LanguageCode = "pt"
    title = "Litecoin - A moeda digital"
    weight = 18

  # Hero section
  [Languages.pt.hero]
    # title = "Global Decentralized Currency"
    # subtitle = "Based on Blockchain Technology"

  # Navigation
  [Languages.pt.navigation]
    brand = "litecoin"
    download = "DESCARREGAR"
    about = "About"
    team = "Team"
    contact = "Contact"

    # postpended links
    [[menu.postpend]]
      url = "https://litecointalk.io/"
      name = "Forum"
      weight = 10


  # About section
  [Languages.pt.about]
    enable = true
    title = "O que é Litecoin?"
    subtitle = "Litecoin é uma moeda ponto-a-ponto baseada na Internet que permite pagamentos instantâneos com um custo próximo à zero para qualquer indivíduo no mundo. Litecoin é uma rede de pagamentos mundial, totalmente descentralizada e sem autoridades centrais. A matemática mantém a rede segura e favorece os indivíduos a manterem controle de suas próprias finanças. Litecoin possui confirmação de transações mais rápidas e melhor eficiência de armazenamento comparado com a moeda líder também baseada na matemática. Com considerável suporte da indústria, volume de negociações e liquidez, Litecoin é uma ferramenta de comércio que complementa o Bitcoin."

    [[Languages.pt.about.row]]
      [[Languages.pt.about.row.list]]
        icon = "fa-group"
        title = "Comunidade"
        description =  '<p class="text-no-margin text-left text-muted">Existe um número crescente de comunidades Litecoin onde você pode encontrar suporte. Você pode visitar: </p><ul class="text-muted text-left "> <li><a href="https://litecointalk.org">Fóruns Litecoin</a></li> <li><a href="http://www.reddit.com/r/litecoin">Comunidade Reddit de Litecoin</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">Procurar Usuários em Twitter</a></li> <li>Participar nos canais da <a href="http://freenode.net/" rel="nofollow">IRC FreeNode:</a> <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (para usuários em geral) y <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (para desenvolvedores).</li> </ul>'

      [[Languages.pt.about.row.list]]
        icon = "fa-laptop"
        title = "Recursos"
        description = 'Você pode acessar as informações gerais, lista de sítios, e lista de câmbio, suportadas por Litecoin em: <a href="http://litecoin.info">Litecoin Wiki</a>. <br> As estatísticas atualizadas da rede podem ser encontradas em: <a href="http://ltc.block-explorer.com/charts">Gráficos de Explorador de Blocos Litecoin</a>. <br> Os códigos fonte Litecoin e outros projetos relacionados encontram-se disponíveis em: <a href="https://github.com/litecoin-project">GitHub.com/litecoin-project</a>.'

      [[Languages.pt.about.row.list]]
        icon = "fa-heart"
        title = "Programa de código-aberto."
        description = "Litecoin é um programa de código-aberto lançado sob a licença MIT/X11 que garante a você o poder de executar, modificar e copiar o programa, bem como distribuí-lo, a seu critério, versões modificadas do mesmo. O programa é lançado através de um processo transparente que permite verificação independente dos binários e de seus correspondentes códigos-fonte."

    [[Languages.pt.about.row]]
      [[Languages.pt.about.row.list]]
        icon = "fa-link"
        title = "Corrente de Blocos ou Block-chain"
        description = "A Corrente de Blocos da Litecoin é capaz de lidar com um volume maior de transações do que o seu homólogo - Bitcoin. Graças à geração mais frequente de blocos, a rede suporta mais transações sem ter que modificar o software no futuro. <br />Em consequência, os comerciantes obtêm confirmações mais rápidas, enquanto ainda têm a capacidade de esperar por mais confirmações ao vender itens mais custosos."

      [[Languages.pt.about.row.list]]
        icon = "fa-lock"
        title = "Codificação da Carteira"
        description = "A codificação da carteira permite que você possa segurar suas chaves privadas na carteira, e assim poderá visualizar as transações e seu saldo de conta, mas é obrigatório inserir sua senha antes de gastar suas litecoins. <br />Isso serve não apenas como proteção para vírus e troianos, mas também como um controle de conformidade antes de enviar os pagamentos."

      [[Languages.pt.about.row.list]]
        icon = "fa-money"
        title = "Recompensa"
        description = "Os mineiros inicialmente gerarão 25 moedas por bloco. A quantidade de moedas geradas fica reduzida à metade a cada 4 anos (840.000 blocos). <br />Portanto, a rede Litecoin é projetada para produzir cerca de 4 vezes o número de unidades do que Bitcoin, ou cerca de 84 milhões de litecoins."

  # download section
  [Languages.pt.download]
    enable = true
    gpg = "GPG Signatures"
    download = "DESCARREGAR"
    source = " FONTE"
    releaseNotes = "Informações da versão"
    upgradeNotes = "Informações da atualização"

    windows = "para Windows"
    mac = "para Mac OS X"
    linux = "para Linux"
    android = "Litecoin para Android"
    blackberry = "Litecoin para Blackberry"
    electrum = "Electrum Litecoin"


  # Contact section
  [Languages.pt.contact]
    enable = true
    title = "Contact us"
    subtitle  = 'Você pode entrar em contato com a equipe de desenvolvimento da Litecoin em: <a href="mailto:contact@litecoin.org">contact@litecoin.org</a>.'

  # Footer section
  [Languages.pt.footer]
    enable = true
    copyright = 'Copyright &copy; 2011-2016 Litecoin Project. Todos os direitos reservados.'
