# RUSSIAN _____________________________
  [Languages.ru]
    lang = "Русский"
    LanguageCode = "ru"
    title = "Litecoin - децентрализованная криптовалюта с открытым исходным кодом"
    weight = 19

  # Hero section
  [Languages.ru.hero]
    # title = "Global Decentralized Currency"
    # subtitle = "Based on Blockchain Technology"

  # Navigation
  [Languages.ru.navigation]
    brand = "litecoin"
    download = "СКАЧАТЬ"
    about = "About"
    team = "Team"
    contact = "Contact"

    # postpended links
    [[menu.postpend]]
      url = "https://litecointalk.io/"
      name = "Forum"
      weight = 10


  # About section
  [Languages.ru.about]
    enable = true
    title = "Что такое Litecoin?"
    subtitle = "Litecoin - одноранговая интернет-валюта, которая включает в себя, почти нулевые по стоимости платежи в любую точку мира. Litecoin - это открытый исходный код, глобальная платежная сеть, которая полностью децентрализована и не имеет контроля со стороны любых центральных властей. Математика защищает сеть и уполномочивает людей управлять своими собственными финансами. Litecoin отличается более быстрым временем подтверждения транзакций и повышенной эффективностью хранения, чем ведущая, основанная на математике валюта. С серьёзной отраслевой поддержкой, торговым оборотом и ликвидностью, Litecoin является проверенным средством для коммерции в дополнение к Bitcoin."

    [[Languages.ru.about.row]]
      [[Languages.ru.about.row.list]]
        icon = "fa-group"
        title = "Сообщество"
        description =  '<p class="text-no-margin text-left text-muted">Следующие сообщества Litecoin, где вы можете найти ответы на любые вопросы: </p><ul class="text-muted text-left "> <li><a href="https://litecointalk.org">Форумы Litecoin</a></li> <li><a href="http://www.reddit.com/r/litecoin">Сообщество Litecoin Reddit</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">Поиск пользователей на Twitter</a></li> <li>Присоединяйтесь к сети <a href="http://freenode.net/" rel="nofollow">IRC FreeNode</a>, канал <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (для общих пользователей) и <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (для разработчиков).</li> </ul>'

      [[Languages.ru.about.row.list]]
        icon = "fa-laptop"
        title = "Ресурсы"
        description = 'Общую информацию, перечень сайтов и бирж, которые поддерживают Litecoin, можно найти на <a href="http://litecoin.info">Litecoin Wiki</a>. <br> Статистика сети регулярно обновляется на <a href="http://ltc.block-explorer.com/charts">Litecoin Block Explorer Charts</a>. <br> Исходный код Litecoin и связанные с ним проекты доступны на <a href="https://github.com/litecoin-project">GitHub.com/litecoin-project</a>.'

      [[Languages.ru.about.row.list]]
        icon = "fa-heart"
        title = "Программное обеспечение с открытым исходным кодом"
        description = "Litecoin - это бесплатный проект программного обеспечения с открытым исходным кодом, выпущенный в соответствии с лицензией MIT/X11, которая дает Вам право выполнять, изменять, и копировать программное обеспечение, а так же распространять, по Вашему желанию, измененные копии программного обеспечения. Прозрачность выпуска новых версий позволяет осуществлять независимую проверку бинарных модулей и соответствующего исходного кода."

    [[Languages.ru.about.row]]
      [[Languages.ru.about.row.list]]
        icon = "fa-link"
        title = "Цепочка Блоков"
        description = "Цепочка блоков Litecoin способна обрабатывать более высокий объем транзакций, чем ее аналог – Bitcoin. Благодаря более частой генерации блоков, сеть способна поддерживать больший объем транзакций без необходимости каких либо изменений программного обеспечения в будущем. <br />В результате торговцы получают более быстрое время подтверждения, без необходимости ожидания множества подтверждений при большом количестве проданных позиций."

      [[Languages.ru.about.row.list]]
        icon = "fa-lock"
        title = "Шифрование Кошелька"
        description = "Шифрование бумажника позволяет Вам защищать свой бумажник, таким образом, чтобы Вы можете просмотреть транзакции и Ваш баланс счета, но обязаны вводить Ваш пароль всегда, перед тем как решите потратить litecoins.<br />Это обеспечивает защиту от вирусов и троянов, ворующих кошельки, а также проверки Вашего здравомыслия перед отправкой платежа."

      [[Languages.ru.about.row.list]]
        icon = "fa-money"
        title = "Вознаграждение за майнинг"
        description = "За каждый сгенерированный блок майнеры получают 25 litecoin (LTC) за найденный блок и сумма вознаграждения уменьшается вдвое каждые 4 года (каждые 840 000 блоков). <br />Таким образом, максимальное количество монет в сети Litecoin составляет приблизительно 84 миллиона, что в четыре раза превышает количество монет в сети Bitcoin."

  # download section
  [Languages.ru.download]
    enable = true
    gpg = "GPG Signatures"
    download = "СКАЧАТЬ"
    source = "ИСХОДНЫЙ КОД"
    releaseNotes = "Информация о версии"
    upgradeNotes = "Информация об обновлении"

    windows = "для Windows"
    mac = "для Mac OS X"
    linux = "для Linux"
    android = "Litecoin для Android"
    blackberry = "Litecoin для Blackberry"
    electrum = "Electrum Litecoin"


  # Contact section
  [Languages.ru.contact]
    enable = true
    # title = "Contact us"
    subtitle  = 'Вы можете связаться с разработчиками проекта Litecoin по электронной почте: <a href="mailto:contact@litecoin.org">contact@litecoin.org</a>.'

  # Footer section
  [Languages.ru.footer]
    enable = true
    copyright = 'Все права защищены &copy; 2011-2016 Проект Litecoin'
